export const Messages = {
  BAN_FOR_SEC: 60 * 1000,
  MAX_REQUEST: 10,
  BOOKING_ALREADY_EXISTS: "Booking already exists for this user and book",
  SERVER_ERROR: "An error occurred on the server",
  INTERNAL_SERVER_ERROR_MESSAGE:
    "Internal server error. Please try again later.",
  BOOKING_NOT_FOUND: "Booking not found",
  USER_NOT_FOUND: "User not found",
  ALREADY_BORROWED: "Already borrowed !",
  BORROWED_SUCCESSFULLY: "Borrowed Successfully",
  CREATING_BOOK: "Creating book",
  FETCHING_BOOKS: "Fetching books",
  FETCHING_BOOK_WITH_ID: "Fetching book with id",
  CREATING_BOOKING_FOR_USERID: "Creating booking for userId",
  BOOK_ID: "bookId",
  RETURNING_BOOKING_FOR_USERID: "Returning booking for userId",
  CREATING_USER_WITH_NAME: "Creating user with name",
  FETCHING_USERS: "Fetching users",
  FETCHING_USER_WITH_ID: "Fetching user with id",
  BORROWING_BOOK_FOR_USERID: "Borrowing book for userId:",
  RETURNING_BOOK_FOR_USERID: "Returning book for userId",
  BOOKING_SUCCESSFULLY: "Booking Successfully",
  TOO_MANY_REQUEST: "Too many requests, please try again later.",
};
